version: "3.9"

services:
  react-app:
    container_name: "react-app"
    build:
      context: ./client/
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    command: yarn start
    depends_on:
      - api-server

  api-server:
    container_name: "api-server"
    build:
      context: ./server/
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - mern-app
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
